python generate.py --train_data ani_sketch_MJ
python generate.py --train_data Disney_sketch_MJ
python generate.py --train_data sketch_MJ
python generate.py --train_data Rough_sketch_MJ
python generate.py --train_data GHIBLI_sketch_MJ
python generate.py --train_data pencil_sj
python generate.py --train_data low_sj
python generate.py --train_data apd
python generate.py --train_data cufs